### ISSUE TITLE
Create first panel

### ISSUE THREAD

**Issue by menor** [resmio/widget#101]
This is a mega issue that involves a lot of other issues, so we use this just as a place to put the designs and a checklist of stuff that needs to be done.
- [x] Define Min & Max -height and -width for the widget #94
- [x] Implement a panel component #90
- [x] Implement the header component #91
- [x] Implement the footer component #92
- [x] Implement basic timelist component #99
- [x] Implement the collapsing/expanding logic for the first panel #96
- [x] Put the button from mantecao #93
- [x] Implement the person picker #95
- [x] Inline react-dates #98
- [ ] Implement the filter timelist function #100 
- [ ] Show comment from Holidays & Exceptions #97
